### ISSUE TITLE
Won't load with latest create version

### ISSUE THREAD

**Issue by Aero48** [MythrilBagels/Create-Alloyed#75]
VERSIONS
Minecraft - 1.19.2
Create - 0.5.1a
Flywheel - 0.6.8a
Alloyed - 1.5

DESCRIPTION
Minecraft fails to load Alloyed with the latest version of create.

STEPS TO REPRODUCE
Run the latest versions of Create and Alloyed.

**Comment by TysonTheEmber** [comment]
same here, It crashes when loaded with any create 0.5.1 version. A or B. They both crash.

**Comment by UltrascatterRED** [comment]
I also ran into this issue. Ran Create 5.1 and Create: Alloyed v1.4e together on Minecraft 1.18.2, crashed with a simple "failed to load Create: Alloyed" message. Was not caused by conflicts with additional mods, from what I could glean from the crash log.

**Comment by Barerock** [comment]
All dependents of Create have this issue. It is most likely due to failed version check, which is probably on purpose. With how many changes 0.5.1 makes many dependents may need to be reworked.

**Comment by FortressNebula** [comment]
New update should fix this.

**Comment by Peach774** [comment]
Any fix for the 1.19 version of the mod? that version is still crashing
